name: Publish Image
description: Publish container images to @cloud-city-crafted-images
author: cloud-city-crafted

inputs:
  github-token:
    description: GitHub personal access token (PAT) used to push to the GitHub Container Registry
    default: ''
    required: true
  image-version:
    description: Container image semantic version
    default: 1.0.0
    required: false

runs:
  using: 'composite'

  steps:
    - name: Checkout Image Source
      uses: actions/checkout@v4

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract Image Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }},ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:v${{ inputs.image-version }}
        labels: ${{ steps.meta.outputs.labels }},org.opencontainers.image.source=https://github.com/${{ github.repository }}
